service: rest

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-2
  iamRoleStatements:
      - Effect: Allow
        Action:
            - s3:*
        Resource: '*'
  
functions:
  upload:
    handler: api/external/upload.upload
    description: Submit json file that describes a location.
    events:
      - http: 
          path: upload
          method: POST
          cors: true
  all-locations:
    handler: api/internal/location.all
    description: Get a list of all file names.
    events:
      - http: 
          path: all-locations
          method: GET
          cors: true
  location:
    handler: api/internal/location.location
    description: Get a single location with the key.
    events:
      - http: 
          path: location
          method: GET
          cors: true

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: take-home-bucket
        CorsConfiguration:
          CorsRules:
          - AllowedHeaders: 
              - '*'
            AllowedMethods: 
              - HEAD
              - GET
              - PUT
              - POST
              - DELETE
            AllowedOrigins: 
              - '*'
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
            MaxAge: 3000

plugins:
  - serverless-offline